Simplify styling
NativeScript/nativescript-picker pull request #10
Opened 2019-03-21 16:50 UTC by bundyo

- Add PickerField element selector
- Add PickerPage element that inherits from Page in the modal and a selector for it
- Move the class set on ActionBar and ListView to the aforementioned PickerPage
- Document it

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] All existing tests are passing
- [ ] Tests for the changes are included

## What is the current behavior?
Will describe later

## What is the new behavior?
Will describe later

Fixes/Implements/Closes #[Issue Number].
Will add later

BREAKING CHANGES:
- Moves the classes from the ActionBar and ListView to the PickerPage element

Migration:
- Fix selectors from `ListView.class` to `.class ListView`.

2019-03-22 11:58 UTC, VladimirAmiorkov requested changes
Great PR, all is left is to update the demo, demo-angular and demo-vue with the breaking changes.

2019-03-22 14:36 UTC, VladimirAmiorkov approved these changes

2019-03-26 05:46 UTC, bundyo commented
run ci

2019-03-26 05:48 UTC, bundyo commented
run ci

2019-03-27 06:52 UTC, merged